### ISSUE TITLE
IllegalStateException when no connectivity

### ISSUE THREAD

**Issue by chronvas** [android10/Android-CleanArchitecture-Kotlin#16]
"Unsafe" cast operator should be nullable
Extension `networkInfo` on `context` should return `NetworkInfo?`, otherwise causes runtime crash.

This derrives from the abstract `getSystemService` which is annotated as `Nullable`

Also, as per Kotlin documentation about _"Unsafe" cast operator_ (can be found [here](https://kotlinlang.org/docs/reference/typecasts.html#unsafe-cast-operator))   _In order to match Java cast semantics we have to have nullable type at cast right hand side_

Ways to reproduce, just launch the app with no network connectivity and it crashes with logcat:

```05-13 18:22:12.112 6453-6453/com.fernandocejas.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fernandocejas.sample, PID: 6453
    java.lang.IllegalStateException: (this.getSystemService(C…anager).activeNetworkInfo must not be null
        at com.fernandocejas.sample.core.extension.ContextKt.getNetworkInfo(Context.kt:23)
        at com.fernandocejas.sample.core.platform.NetworkHandler.isConnected(NetworkHandler.kt:29)
        at com.fernandocejas.sample.features.movies.MoviesRepository$Network.movies(MoviesRepository.kt:37)
        at com.fernandocejas.sample.features.movies.GetMovies.run(GetMovies.kt:25)
        at com.fernandocejas.sample.features.movies.GetMovies.run(GetMovies.kt:22)
        at com.fernandocejas.sample.core.interactor.UseCase$execute$job$1.doResume(UseCase.kt:38)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
Device used: Android Emulator API 26

Solution 1:
networkInfo extension should return a nullable type for method named `networkInfo`, Usages of `networkHandler.isConnected` should handle null case

Solution 2:
Wrap it as an Optional

**Comment by chronvas** [comment]
I created a pr for fixing this with Solution 1 https://github.com/android10/Android-CleanArchitecture-Kotlin/pull/17

**Comment by android10** [comment]
@chronvas merged! Thanks for the contribution! :tada:
